# Generated by Django 5.2.6 on 2025-10-01 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('features', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='analysis.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('az', models.TextField()),
                ('en', models.TextField()),
                ('ru', models.TextField()),
                ('priority', models.IntegerField(default=1)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='analysis.function')),
                ('plan', models.ManyToManyField(related_name='questions', to='analysis.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.IntegerField(choices=[(1, 'Not Applicable'), (2, 'Not Implemented'), (3, 'Partially Implemented'), (4, 'Implemented and Functioning'), (5, 'Systematic and Innovative Implementation')])),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='analysis.invoice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='analysis.question')),
            ],
        ),
    ]
