# Generated by Django 5.2.6 on 2025-10-01 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
