# Generated by Django 5.2.6 on 2025-10-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_alter_plan_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='function',
            name='name',
        ),
        migrations.AddField(
            model_name='function',
            name='az',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='function',
            name='en',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='function',
            name='ru',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
