# Generated by Django 5.2.6 on 2025-10-02 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_remove_function_name_function_az_function_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='uid',
            field=models.UUIDField(auto_created=True, default='123456789abcdef123456789abcdef12', editable=False, unique=True),
        ),
    ]
