# Generated by Django 5.2.6 on 2025-10-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_invoice_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='due_date',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
    ]
