# Generated by Django 5.2.6 on 2025-10-02 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_remove_invoice_due_date_alter_invoice_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='uid',
            field=models.UUIDField(auto_created=True, editable=False, unique=True),
        ),
    ]
