# Generated by Django 5.2.6 on 2025-10-02 08:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_alter_invoice_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='uid',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, unique=True),
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='analysis.invoice')),
            ],
        ),
    ]
